In [1]:
import pandas as pd

df = pd.read_csv('diabetes.csv')

print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [2]:
x=df.iloc[:,0:8]
y=df.iloc[:,-1]

In [3]:
x.shape

(768, 8)

In [4]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
print(x_train.shape)
print(x_test.shape)

(514, 8)
(254, 8)


In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
x_train

array([[ 1.89917664, -0.19475093,  1.55717838, ..., -1.04293476,
         1.60661512,  0.06905859],
       [ 0.98286551,  0.64046336, -0.55496107, ..., -0.4148062 ,
         0.62609815,  2.37289284],
       [ 0.06655438, -0.16381707,  0.11203033, ..., -1.29156898,
        -0.02953111,  0.32504017],
       ...,
       [ 1.89917664, -0.62782501,  0.89018698, ...,  1.78364376,
         1.94028358,  0.41036736],
       [-1.1551938 ,  0.6095295 , -3.88991811, ...,  1.36489138,
        -0.78467552, -0.35757739],
       [-1.1551938 ,  0.11458769,  1.44601315, ..., -1.23922494,
        -0.61784129, -1.04019494]])

In [8]:
x_test

array([[ 0.67742846, -0.7206266 , -0.66612631, ...,  0.2656664 ,
        -0.12611934,  0.83700334],
       [-0.54431971, -0.28755252,  0.27877819, ...,  0.4881286 ,
        -0.95150975, -1.04019494],
       [-0.54431971, -0.41128797, -0.3326306 , ..., -0.15308597,
        -0.92224058, -1.04019494],
       ...,
       [-0.84975676, -3.75214514,  0.22319557, ..., -0.55875233,
        -0.50954538, -1.04019494],
       [ 1.28830255,  0.67139722, -0.22146537, ...,  0.38344051,
        -1.00712116,  0.66634895],
       [-0.54431971, -0.62782501, -0.66612631, ..., -1.01676274,
         0.41243326, -0.86954055]])

In [9]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
model=lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [10]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[136,  32],
       [ 34,  52]], dtype=int64)

In [12]:
x_test[y_pred==0]

array([[ 0.67742846, -0.7206266 , -0.66612631, ...,  0.2656664 ,
        -0.12611934,  0.83700334],
       [-0.54431971, -0.28755252,  0.27877819, ...,  0.4881286 ,
        -0.95150975, -1.04019494],
       [-0.54431971, -0.41128797, -0.3326306 , ..., -0.15308597,
        -0.92224058, -1.04019494],
       ...,
       [-0.84975676, -0.81342819,  0.66785651, ...,  0.39652652,
        -0.70272186,  0.83700334],
       [-0.84975676, -3.75214514,  0.22319557, ..., -0.55875233,
        -0.50954538, -1.04019494],
       [-0.54431971, -0.62782501, -0.66612631, ..., -1.01676274,
         0.41243326, -0.86954055]])

In [13]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.7401574803149606

In [14]:
!pip install pickle

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [15]:
import pickle
Model = pickle.dumps(model)

In [16]:
!pip install tkinter

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter


In [17]:
import tkinter

In [18]:
import numpy as np
import tkinter as tk

from tkinter import ttk

win = tk.Tk()

win.title("Diabetes Prediction")
Preg=ttk.Label(win,text="Pregencies")
Preg.grid(row=0,column=0,sticky=tk.W)
Preg_var=tk.StringVar()
Preg_entrybox=ttk.Entry(win,width=16,textvariable=Preg_var)
Preg_entrybox.grid(row=0,column=1)
#Column 2
glucose=ttk.Label(win,text="glucose")
glucose.grid(row=1,column=0,sticky=tk.W)
glucose_var=tk.StringVar()
glucose_entrybox=ttk.Entry(win,width=16,textvariable=glucose_var)
glucose_entrybox.grid(row=1,column=1)
#Column 3
Pres=ttk.Label(win,text="Pressure")
Pres.grid(row=2,column=0,sticky=tk.W)
Pres_var=tk.StringVar()
Pres_entrybox=ttk.Entry(win,width=16,textvariable=Pres_var)
Pres_entrybox.grid(row=2,column=1)
#Column 4
skin=ttk.Label(win,text="skin thin")
skin.grid(row=3,column=0,sticky=tk.W)
skin_var=tk.StringVar()
skin_entrybox=ttk.Entry(win,width=16,textvariable=skin_var)
skin_entrybox.grid(row=3,column=1)
#Column 5
insulin=ttk.Label(win,text="insulin")
insulin.grid(row=4,column=0,sticky=tk.W)
insulin_var=tk.StringVar()
insulin_entrybox=ttk.Entry(win,width=16,textvariable=insulin_var)
insulin_entrybox.grid(row=4,column=1)
#Column 6
bmi=ttk.Label(win,text="bmi")
bmi.grid(row=5,column=0,sticky=tk.W)
bmi_var=tk.StringVar()
bmi_entrybox=ttk.Entry(win,width=16,textvariable=bmi_var)
bmi_entrybox.grid(row=5,column=1)
#Column 7
predi=ttk.Label(win,text="predi")
predi.grid(row=6,column=0,sticky=tk.W)
predi_var=tk.StringVar()
predi_entrybox=ttk.Entry(win,width=16,textvariable=predi_var)
predi_entrybox.grid(row=6,column=1)
#Column 8
age=ttk.Label(win,text="age")
age.grid(row=7,column=0,sticky=tk.W)
age_var=tk.StringVar()
age_entrybox=ttk.Entry(win,width=16,textvariable=age_var)
age_entrybox.grid(row=7,column=1)





def Output():
    k=np.array([[float(Preg_var.get()),float(glucose_var.get()),float(Pres_var.get()),float(skin_var.get()),float(insulin_var.get()),float(bmi_var.get()),float(predi_var.get()),float(age_var.get())]])
    k=sc.transform(k)
    output=lr.predict(k)
    if output==1:
        result='Diabetic'
    else:
        result='Non-Diabetic'
    Predict_entrybox.insert(1,str(result))

Predict_entrybox=ttk.Entry(win,width=16)
Predict_entrybox.grid(row=20,column=1)

Predict_button=ttk.Button(win,text="Predict",command=Output)
Predict_button.grid(row=20,column=0)
win.mainloop()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [19]:
lr.predict([[1,2,3,3,4,5,6,7]])

array([1], dtype=int64)